{% set name = "lb-telemetry" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lb-telemetry-{{ version }}.tar.gz
  sha256: a5b533fc6aaafdfb16e33f7eebd73795b475132472aad90d139f2ac948a9e04f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - setuptools >=30.3.0
    - wheel
    - setuptools-scm >=3.4
    - pip
  run:
    - python >=3.6

test:
  imports:
    - lb_telemetry
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.cern.ch/lhcb/lb-telemetry
  summary: A utility for logging telemetry data from LHCb packages to MONIT
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - chrisburr
    - CameronMcClymont
